name: base
Channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - pip
  - pip:
    - plotly
    - pandas
    - matplotlib
    - scikit-learn
    - numpy
    - statsmodels
    - seaborn
    - scipy
    - sklearn
